### PR TITLE
Closes #364: Address input dialog (Fixes #372)

### LINKED ISSUE #364: Add address input dialog
It should be possible to open a dialog to select between the different input method:
* Paste from clipboard
* Scan QR code
* Add from address book
* Input ENS address

This is used by the address book and in the send funds flow

Most of the functionality can be cherry-picked from 20b5e06cb4e5cf531d90761145f9d8dd66cc7397

Following adjustments need to be made:
- adjust design of the bottom sheet dialog (selection of input method)
- adjust design of ens input (not sure if these exists, so just make it look nice)
- remove hardcoded strings
- (optional) Use abi files to generate encoding and decoding of data for ENS contract interaction.

For design see https://github.com/gnosis/safe/blob/master/specs/send_funds/02_user_interface.rst#13send-eth-enter---bottomsheet

### LINKED ISSUE #372: Clear text when entering a new password
**Describe the bug**
When setting an app pw after a clean install, the user input isn't obfuscated but in clear text.

**To Reproduce**
obvious

**Expected behavior**
The user input is hidden, same like we have it in the current mainnet playstore version.

**Screenshots**
Screenshot_20190522-145417

**Smartphone (please complete the following information):**
 - Device: Gnosis MotoG
 - App Version: 1.3.0-13-gf...-internal (yellow)

### PR DESCRIPTION
**Pull request by rmeissner**
Closes #364, Fixes #372 

Changes proposed in this pull request:
- Add bottom sheet dialog to select address input
- Add ENS input support
- Fix input type bug on password setup (#372)

@gnosis/mobile-devs

### CODE REVIEW

File: app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultEnsRepository.kt [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+            val resolverAddress = resp.result()!!.asEthereumAddress()!!
+            val resolverData = GET_ADDRESS + node.toHexString()
+            ethereumRepository.request(EthCall(transaction = Transaction(address = resolverAddress, data = resolverData))).firstOrError()
+        }.map { resp ->
+            resp.result()!!.asEthereumAddress()!!
+        }
+
+    companion object {
+        private val ENS_ADDRESS = BuildConfig.ENS_REGISTRY.asEthereumAddress()!!
+        private val GET_ADDRESS = "0x3b3b57de"
```
Comment (elgatovital) [inline app/src/main/java/pm/gnosis/heimdall/data/repositories/impls/DefaultEnsRepository.kt]: maybe we should use const here
