### PR TITLE
Closes #262: Ignore duplicate insertions on address book when recovering Safe

### LINKED ISSUE #262: Error on restore Safe
**Describe the bug**
When restoring a Safe, I get "Unexpected error occurred". The Safe is still added.

**To Reproduce**
* Create new Safe with Chrome extension
* Delete Safe
* Restore Safe
(I did the same also for a Safe without a Chrome extension.

**Expected behavior**
No error.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Moto GS5
 - Android Version: 7.1.1
 - App Version 0.7.1-4-g179d983-internal

**Additional context**
-

### PR DESCRIPTION
**Pull request by rmeissner**
Closes #262.

Changes proposed in this pull request:
- When recovering a Safe and the address is already in the Safe it will not be added again
- Added TransactionTriggerManager, when a transaction is submitted it checks for the type and performs an action.
  - ConnectExtension transaction will trigger Safe creation push to the extension
 

@gnosis/mobile-devs

### CODE REVIEW

File: app/src/main/java/pm/gnosis/heimdall/helpers/TransactionTriggerManager.kt [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+    override fun onTransactionSubmitted(safeAddress: Solidity.Address, transaction: SafeTransaction, chainHash: String) {
+        transactionInfoRepository.parseTransactionData(transaction)
+            .flatMapCompletable {
+                when (it) {
+                    is TransactionData.ConnectExtension -> notifySafeCreated(safeAddress, it.extension)
+                    else -> Completable.complete()
+                }
+            }
+            .subscribe()
```
Comment (fmrsabino) [inline app/src/main/java/pm/gnosis/heimdall/helpers/TransactionTriggerManager.kt]: Should the app crash if `onError` is called here?
