### PR TITLE
Closes #415 and Closes #414: Token payment - replace authenticator and add authenticator

### LINKED ISSUE #414: Token Payment: Connect browser extension
In the process of connecting the browser extension it should be possible to change the payment token for this Safe.

See epic.

### ToDos:
- [ ] Adjust connect browser extension flow to allow changing token via token payment selection screen with balances (#411)

### LINKED ISSUE #415: Token Payment: Replace browser extension
In the process of replacing the browser extension it should be possible to change the payment token for this Safe.

See epic.

### ToDos:
- [ ] Adjust replace browser extension flow to allow changing token via token payment selection screen with balances (#411)

### LINKED ISSUE #453: "Continue" button is not clickable on address step if you click back on Authenticator step
**Describe the bug**
When recovering a safe, if you click back on the Authenticator/Scan QR step, the button 'Continue' on address step is not clickable. If you input an address again, the button is clickable again

**To Reproduce**
1. Go to safe recovery
2. Input an address
3. Click 'Continue'
4. Click back

**Expected behavior**
'Continue' button is clickable

**Smartphone (please complete the following information):**
 - Device: Motorola G7 Power
 - Android Version: Android 9
 - App Version: 1.7.1

### LINKED ISSUE #458: KeyCard: Allow to remove 2FA
It should be possible to remove the 2FA

### LINKED ISSUE #474: KeyCard: Complete design
The first version is missing some screens and design components (e.g. #462) All flows should be according to Zeplin.

### PR DESCRIPTION
**Pull request by elgatovital**
Closes #414.
Closes #415.
Closes #453.
Closes #458.
Closes #474.

Changes proposed in this pull request:
- Refactor replace authenticator flow

@gnosis/mobile-devs

### CODE REVIEW

File: app/src/main/java/pm/gnosis/heimdall/ui/dialogs/base/ConfirmationDialog.kt [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    }
+
+    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
+        return inflater.inflate(R.layout.screen_confirmation_dialog, container, false)
+    }
+
+    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+        super.onViewCreated(view, savedInstanceState)
+        arguments?.let {
+            congratulations_text.text = getString(it[ARG_TEXT_RES] as Int)
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/dialogs/base/ConfirmationDialog.kt]: why not use `getInt()`?

File: app/src/main/java/pm/gnosis/heimdall/ui/dialogs/base/ConfirmationDialog.kt [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+            congratulations_check.setImageResource(it[ARG_IMAGE_RES] as Int)
+        }
+    }
+
+    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
+        val dialog = super.onCreateDialog(savedInstanceState)
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
+            with(dialog) {
+                window?.statusBarColor = context.getColorCompat(R.color.white)
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/dialogs/base/ConfirmationDialog.kt]: Maybe put this in a utils (not necessarily in this PR) and also use it in the ViewModelActivity for `colorStatusBar`

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt [hunk 3]
```diff
@@ -381,7 +382,10 @@ class SafeMainActivity : ViewModelActivity<SafeMainContract>() {
                         )
                     }
                     R.id.safe_details_menu_replace_browser_extension -> selectedSafe?.let { safe ->
-                        startActivity(ReplaceExtensionPairingActivity.createIntent(this, safe.address()))
+
+                        startActivity(ReplaceExtensionStartActivity.createIntent(this, safe.address()))
+
+                        //startActivity(ReplaceExtensionPairingActivity.createIntent(this, safe.address()))
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/main/SafeMainActivity.kt]: remove comment

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+    override fun layout() = R.layout.screen_replace_extension_qr
+
+    override fun inject(component: ViewComponent) = viewComponent().inject(this)
+
+    override fun screenId() = ScreenId.REPLACE_BROWSER_EXTENSION_QR
+
+    override fun onCreate(savedInstanceState: Bundle?) {
+        super.onCreate(savedInstanceState)
+
+        val safeAddress = (intent.extras[EXTRA_SAFE_ADDRESS] as String)?.asEthereumAddress()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt]: same here, why not `getString`?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+        safeAddress?.let {
+            viewModel.setup(it)
+        } ?: finish()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt]: since you do not `return` here the observer method will still be called even without the viewModel being setup, is this expected?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt [hunk 6]
```diff
@@ -0,0 +1,185 @@
...
+                        snackbar(coordinator, R.string.error_pairing_devices)
+                        Timber.e(it.error)
+                    }
+                }
+            }
+        })
+
+        extensionLink.apply {
+            this.text = SpannableStringBuilder(Html.fromHtml(getString(R.string.pairing_first_step)))
+            setOnClickListener { shareExternalText(BuildConfig.CHROME_EXTENSION_URL, "Browser Extension URL") }
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt]: Should `"Browser Extension URL"` be in the strings.xml?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt [hunk 7]
```diff
@@ -0,0 +1,185 @@
...
+        }
+    }
+
+    override fun onStart() {
+        super.onStart()
+
+
+        backArrow.setOnClickListener {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt]: the extensionLink click listener is set in the onCreate, do we want to do all in the same place (doesn't really matter which one)?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt [hunk 8]
```diff
@@ -0,0 +1,185 @@
...
+}
+
+abstract class ReplaceExtensionQrContract : ViewModel() {
+
+    abstract val observableState: LiveData<ViewUpdate>
+
+    abstract fun setup(safeAddress: Solidity.Address)
+
+    /**
+     * @param signingSafe to indicate which key should be used for pairing. @null if a new key should be generated
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt]: This docs don't fit to the function

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt [hunk 9]
```diff
@@ -0,0 +1,185 @@
...
+
+    private lateinit var safeAddress: Solidity.Address
+
+    override fun setup(safeAddress: Solidity.Address) {
+
+        this.safeAddress = safeAddress
+    }
+
+    override fun pair(payload: String) {
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionQrActivity.kt]: If we call `pair` again while a pairing call is still in progress, should we cancel the previous one?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 10]
```diff
@@ -0,0 +1,211 @@
...
+
+        viewModel.setup(safe)
+
+        bottomPanel.disabled = true
+
+        viewModel.observableState.observe(this, Observer {
+
+            if (it.sufficient) {
+                bottomPanel.disabled = false
+                feesError.visibility = View.GONE
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: we have an extension called `visible()`

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 11]
```diff
@@ -0,0 +1,211 @@
...
+                    paymentToken.displayString(currentBalance),
+                    ERC20TokenWithBalance(paymentToken, gasFee).displayString(roundingMode = RoundingMode.UP),
+                    paymentToken.displayString(currentBalance - gasFee),
+                    paymentToken.symbol,
+                    currentBalance > gasFee
+
+                )
+            )
+
+            Timber.d(executeInfo.gasPrice.toString())
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: Debug print

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 12]
```diff
@@ -0,0 +1,211 @@
...
+
+    private lateinit var safeAddress: Solidity.Address
+
+    override fun setup(safeAddress: Solidity.Address) {
+        this.safeAddress = safeAddress
+    }
+
+    override fun estimate() {
+
+        viewModelScope.launch {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: Same here, should we cancel it if it is already running? (or not run it again)

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 13]
```diff
@@ -0,0 +1,211 @@
...
+
+            Timber.d(executeInfo.gasPrice.toString())
+        }
+    }
+
+    companion object {
+        private const val BALANCE_REQUEST_INTERVAL_SECONDS = 10L
+    }
+}
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: In general in this PR there are a lot of whitelines

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 14]
```diff
@@ -0,0 +1,211 @@
...
+        viewModelScope.launch {
+
+            val safeInfo = gnosisSafeRepository.loadInfo(safeAddress).awaitFirst()
+            val paymentToken = tokenRepository.loadPaymentToken(safeAddress).await()
+
+
+            val balance = tokenRepository.loadTokenBalances(safeAddress, listOf(paymentToken))
+                .repeatWhen { it.delay(BALANCE_REQUEST_INTERVAL_SECONDS, TimeUnit.SECONDS) }
+                .retryWhen { it.delay(BALANCE_REQUEST_INTERVAL_SECONDS, TimeUnit.SECONDS) }
+                .awaitFirst()[0]
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: If we `awaitFirst()` this is not really repeating, right? The UI should keep updating over time (not only once).

File: app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt [hunk 15]
```diff
@@ -167,6 +168,18 @@ class ReviewTransactionActivity : ViewModelActivity<ReviewTransactionContract>()
         }
     }
 
+    override fun onConfirmationDialogDismiss() {
+        // If we have a reference id then we have been opened from a external request and should just close the screen without opening a new one
+        if (referenceId ?: 0 < 0)
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt]: shouldn't we have an else? also why `< 0`?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt (hunk 14 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: should we also update gas fee value using same update interval?

File: app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt (hunk 15 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt]: default value of referenceId should be -1. referenceId ?: -1 < 0
Else case here should finish current activity.

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt (hunk 14 above)
Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: hmmm maybe that is a good idea ... even so it might alos be confusing. But it is more correct ... so I would vote for yes. @tschubotz any preferences?

File: app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt [hunk 16]
```diff
@@ -19,14 +23,27 @@ import pm.gnosis.heimdall.ui.addressbook.list.AddressBookActivity
...
-import pm.gnosis.svalinn.common.utils.openUrl
-import pm.gnosis.svalinn.common.utils.snackbar
-import pm.gnosis.svalinn.common.utils.toast
+import pm.gnosis.svalinn.common.utils.*
 import pm.gnosis.svalinn.utils.ethereum.ERC67Parser
 import pm.gnosis.utils.asEthereumAddress
 import java.lang.ref.WeakReference
 
+
+fun colorStatusBar(window: Window, @ColorRes color: Int = R.color.primary) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/utils/AppUtils.kt]: 👍 

could this be an extension function of `window` or `fragment` or similar?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 17]
```diff
@@ -0,0 +1,184 @@
...
+                    it[0]
+                }
+                .openSubscription()
+
+
+            balanceChannel.consumeEach {
+
+                val balance = it.second ?: BigInteger.ZERO
+
+                val executeInfo = transactionExecutionRepository.loadExecuteInformation(safeAddress, paymentToken.address, transaction).await()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: `transactionExecutionRepository.loadExecuteInformation` includes the paymentToken balance ... so it is not really necessary to call `tokenRepository.loadTokenBalances`

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 18]
```diff
@@ -0,0 +1,111 @@
...
+                    }
+                    progressBar.visibility = View.GONE
+                    balanceBeforeValue.text = it.balanceBefore
+                    feesValue.text = it.fee.underline()
+                    balanceAfterValue.text = it.balanceAfter
+                }
+            }
+        })
+
+        lifecycleScope.launchWhenStarted {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: What is the advantage of doing this vs just calling it in `onStart` (since the view model method uses the viewmodel scope anyways)

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt [hunk 19]
```diff
@@ -0,0 +1,111 @@
...
+
+        backArrow.setOnClickListener {
+            finish()
+        }
+
+        feesValue.setOnClickListener {
+            startActivity(PaymentTokensActivity.createIntent(this, safe))
+        }
+
+        disposables += feesInfo.clicks()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/extension/ReplaceExtensionStartActivity.kt]: Feels weird that we are mixing rx clicks and click listener

File: app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt [hunk 20]
```diff
@@ -167,6 +168,21 @@ class ReviewTransactionActivity : ViewModelActivity<ReviewTransactionContract>()
         }
     }
 
+    override fun onConfirmationDialogDismiss() {
+        // If we have a reference id then we have been opened from a external request and should just close the screen without opening a new one
+        if (referenceId ?: -1 < 0) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt]: can we not just say if we have a referenceId than we should finish?
e.g.
```
referenceId?.let{ finish() } ?: run { startActivity(...) }
```

**Comment by rmeissner** [comment]
What about tests?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt (hunk 17 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: balance could be changed from outside. Should we recalculate estimate only if balance was changed? Or should we just periodically call loadExecuteInformation?

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Either way the call to `loadExecuteInformation` includes the balance, so no need to load it before

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 21]
```diff
@@ -0,0 +1,184 @@
...
+
+                    )
+                )
+            }
+        }
+    }
+
+    override fun pair(payload: String) {
+
+        viewModelScope.launch(Dispatchers.IO + errorHandler) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: we should probably use appDispatchers here

Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: yes

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/ConnectExtensionStartActivity.kt [hunk 22]
```diff
@@ -0,0 +1,162 @@
...
+                        }
+                    }
+                }
+
+            }
+        })
+
+        swipeToRefresh.setOnRefreshListener {
+            viewModel.estimate()
+            swipeToRefresh.isRefreshing = false
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/ConnectExtensionStartActivity.kt]: Why is this required?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 23]
```diff
@@ -0,0 +1,172 @@
...
+
+    private lateinit var safeAddress: Solidity.Address
+
+    private lateinit var paymentToken: ERC20Token
+    private lateinit var pairingTransaction: SafeTransaction
+
+
+    override fun setup(safeAddress: Solidity.Address) {
+        this.safeAddress = safeAddress
+        runBlocking(appDispatcher.background + errorHandler) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Calling `runBlocking` on the mainthread, doesn't this cause the UI to be blocked until the coroutine finishes?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 24]
```diff
@@ -0,0 +1,172 @@
...
+            loadPaymentToken()
+            buildPairingTransaction()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Why do we have to do this here vs doing it in the estimate function

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Same for the payment token

Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: we have to do it only once. Payment token and pairing transaction remain same. Only gas price estimate can change

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/ConnectExtensionStartActivity.kt (hunk 22 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/ConnectExtensionStartActivity.kt]: if user decides to refresh and update the gas price estimate

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/ConnectExtensionStartActivity.kt]: ahh you only use pull to refresh to trigger the loading, not to show that it is loading

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt (hunk 24 above)
Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: `buildPairingTransaction` is performing a network call that might fail and there is no way to retry this right now. Also payment token might actualy change, since you can change the payment token in the screen and currently it would not be reloaded.

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 25]
```diff
@@ -0,0 +1,172 @@
...
+        )
+    }
+
+    override fun estimate() {
+
+        viewModelScope.launch(appDispatcher.background + errorHandler) {
+
+            val executeInfo = transactionExecutionRepository.loadExecuteInformation(safeAddress, paymentToken.address, pairingTransaction).await()
+
+            val gasFee = with(executeInfo) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: executeInfo has a method for this calculation

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt (hunk 24 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: moved payment token & pairing transaction calls to estimate method

**Comment by rmeissner** [comment]
When changing the payment token the estimates screen does not immediately update (no loading spinner or similar). So you can potentially continue even so you don't have enough funds with the new payment method. (Tested with "Connect authenticator" flow)

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 26]
```diff
@@ -0,0 +1,157 @@
...
+                safeInfo.owners.subList(2, safeInfo.owners.size).toSet(),
+                setOf(owner, extension)
+            )
+
+            val executeInfo = transactionExecutionRepository.loadExecuteInformation(safeAddress, paymentToken.address, pairingTransaction).await()
+            val gasFee = executeInfo.gasCosts()
+
+            _state.postValue(
+                ViewUpdate.Balance(
+                    false,
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: There is never the Balance update with loading = true

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 27]
```diff
@@ -137,7 +137,7 @@ class PairingAuthenticatorViewModel @Inject constructor(
 
             val info =
                 try {
-                    gnosisSafeRepository.loadAuthenticatorInfo(safeInfo.owners[1])
+                    gnosisSafeRepository.loadAuthenticatorInfo(safeInfo.owners[0])
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Is there not a way how we can do that without "guessing" at what index the extension address is?

Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: we have to extend our db schema and save address mapings. It seems that currently there is no way how to tell which address in the owner list is a 2fa device

Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: SafeInfoDb could include 2fa address.

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: You could just check if we have an authenticator info for each owner in the list and take the first we find

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: I would not add it to the SafeInfoDb, since we would need to update over time (as we discussed before)

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: see https://github.com/gnosis/safe-android/blob/master/app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/helpers/SubmitTransactionHelper.kt#L232

File: app/src/main/AndroidManifest.xml [hunk 28]
```diff
@@ -194,18 +200,36 @@
             android:theme="@style/GreyBackgroundTheme"
             android:windowSoftInputMode="adjustResize" />
 
+
+        <activity
+            android:name=".ui.safe.connect.Connect2FaStartActivity"
```
Comment (rmeissner) [inline app/src/main/AndroidManifest.xml]: Why is this not in the pairing package? It even uses the viewmodel from there

File: app/src/main/AndroidManifest.xml [hunk 29]
```diff
@@ -194,18 +200,36 @@
...
+            android:theme="@style/WhiteTheme" />
+
+        <activity
+            android:name=".ui.safe.recover.extension.Replace2FaStartActivity"
+            android:screenOrientation="portrait"
+            android:theme="@style/WhiteTheme" />
+
         <activity
-            android:name=".ui.safe.recover.extension.ReplaceAuthenticatorSubmitActivity"
+            android:name=".ui.safe.connect.Remove2FaStartActivity"
```
Comment (rmeissner) [inline app/src/main/AndroidManifest.xml]: Same here

File: app/src/main/AndroidManifest.xml [hunk 30]
```diff
@@ -194,18 +200,36 @@
...
+            android:screenOrientation="portrait"
+            android:theme="@style/WhiteTheme" />
+
+
+        <activity
+            android:name=".ui.safe.recover.extension.ReplaceAuthenticatorRecoveryPhraseActivity"
```
Comment (rmeissner) [inline app/src/main/AndroidManifest.xml]: Should we rename the `extension` to `authenticator`?

File: app/src/main/java/pm/gnosis/heimdall/di/components/ViewComponent.kt [hunk 31]
```diff
@@ -134,8 +138,10 @@ interface ViewComponent {
     fun inject(activity: RecoverSafeIntroActivity)
     fun inject(activity: RecoverSafeRecoveryPhraseActivity)
     fun inject(activity: RecoveryPhraseIntroActivity)
-    fun inject(activity: ReplaceAuthenticatorSubmitActivity)
     fun inject(activity: ReplaceAuthenticatorRecoveryPhraseActivity)
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/di/components/ViewComponent.kt]: Why are there new lines here?

File: app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt [hunk 32]
```diff
@@ -198,6 +198,7 @@ class ApplicationModule(private val application: Application) {
             }
         }.build()
 
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt]: Could we try to avoid multiple new lines (or have them everywhere, I am fine either way)

File: app/src/main/java/pm/gnosis/heimdall/di/modules/InterceptorsModule.kt [hunk 33]
```diff
@@ -37,4 +38,15 @@ class InterceptorsModule {
             it.proceed(request.newBuilder().url(url).build())
         }
     }
+
+    @Provides
+    @Singleton
+    @IntoMap
+    @IntKey(1)
+    @Named(INTERCEPTORS_WITH_PRIORITY)
+    fun providesLoggingInterceptor(): Interceptor {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/di/modules/InterceptorsModule.kt]: Alternatively we could make the returned Interceptor nullable and use `mapNotNull` to avoid adding it if not in debug mode

File: app/src/main/java/pm/gnosis/heimdall/di/modules/ViewModelFactoryModule.kt [hunk 34]
```diff
@@ -226,16 +225,34 @@ abstract class ViewModelFactoryModule {
     @ViewModelKey(RecoverSafeRecoveryPhraseContract::class)
     abstract fun bindsRecoverInputRecoveryPhraseContract(viewModel: RecoverSafeRecoveryPhraseViewModel): ViewModel
 
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/di/modules/ViewModelFactoryModule.kt]: New lines

File: app/src/main/java/pm/gnosis/heimdall/ui/authenticator/ConnectAuthenticatorActivity.kt [hunk 35]
```diff
@@ -57,6 +59,14 @@ class ConnectAuthenticatorViewModel @Inject constructor(
                             txData = TransactionData.ConnectAuthenticator(info.authenticator.address)
                         )
                     )
+//                    viewAction = ViewAction.StartActivity(
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/authenticator/ConnectAuthenticatorActivity.kt]: Unused code?

File: app/src/main/java/pm/gnosis/heimdall/ui/keycard/KeycardIntroActivity.kt [hunk 36]
```diff
@@ -24,6 +25,12 @@ class KeycardIntroActivity : BaseActivity(), KeycardPairingDialog.PairingCallbac
         super.onCreate(savedInstanceState)
         setContentView(R.layout.layout_keycard_intro)
 
+        if (intent.getBooleanExtra(EXTRA_ONBOARDING, false)) {
+            step_indicator.visibility = View.VISIBLE
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/keycard/KeycardIntroActivity.kt]: there is a `isVisible` method

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt [hunk 37]
```diff
@@ -0,0 +1,129 @@
...
+    override fun onCreate(savedInstanceState: Bundle?) {
+        super.onCreate(savedInstanceState)
+
+        safe = intent.getStringExtra(EXTRA_SAFE_ADDRESS)?.asEthereumAddress() ?: run {
+            finish()
+            return
+        }
+
+        bottomPanel.disabled = true
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: new lines

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt [hunk 38]
```diff
@@ -0,0 +1,129 @@
...
+                    }
+                    progressBar.visibility = View.GONE
+                    balanceBeforeValue.text = it.balanceBefore
+                    feesValue.text = it.fee.underline()
+                    balanceAfterValue.text = it.balanceAfter
+                }
+            }
+        })
+
+        lifecycleScope.launchWhenStarted {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: Is this scope even required here? `viewModel.estimate()` internally uses another coroutine, so this scope might not have any effect

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt [hunk 39]
```diff
@@ -0,0 +1,129 @@
...
+
+        viewModel.observableState.observe(this, Observer {
+
+            when(it) {
+
+                is PairingAuthenticatorContract.ViewUpdate.Balance -> {
+
+                    if (it.sufficient) {
+                        bottomPanel.disabled = false
+                        feesError.visibility = View.GONE
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: could use `isVisible` function here

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt [hunk 40]
```diff
@@ -0,0 +1,129 @@
...
+            startActivity(ConnectAuthenticatorActivity.createIntent(this, safe))
+        }
+    }
+
+    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
+        super.onActivityResult(requestCode, resultCode, data)
+        handleQrCodeActivityResult(requestCode, resultCode, data, onQrCodeResult = { viewModel.pair(it) })
+    }
+
+    private fun onLoading(isLoading: Boolean) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: Unused code?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 41]
```diff
@@ -0,0 +1,193 @@
...
+    private val accountsRepository: AccountsRepository,
+    private val tokenRepository: TokenRepository,
+    private val transactionExecutionRepository: TransactionExecutionRepository,
+    private val pushServiceRepository: PushServiceRepository,
+    private val moshi: Moshi,
+    private val appDispatcher: ApplicationModule.AppCoroutineDispatchers
+) : PairingAuthenticatorContract() {
+
+    private val errorHandler = CoroutineExceptionHandler { _, e ->
+        viewModelScope.launch {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Should we propagate the error to the user?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt [hunk 42]
```diff
@@ -0,0 +1,135 @@
...
+            viewModel.loadAuthenticatorInfo()
+        }
+    }
+
+    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
+        super.onActivityResult(requestCode, resultCode, data)
+        handleQrCodeActivityResult(requestCode, resultCode, data, onQrCodeResult = { viewModel.pair(it) })
+    }
+
+    private fun onLoading(isLoading: Boolean) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt]: unused code?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt [hunk 43]
```diff
@@ -0,0 +1,135 @@
...
+import kotlinx.android.synthetic.main.include_transfer_summary.transfer_data_fees_info as feesInfo
+import kotlinx.android.synthetic.main.include_transfer_summary.transfer_data_fees_value as feesValue
+import kotlinx.android.synthetic.main.include_transfer_summary.transfer_data_safe_balance_after_value as balanceAfterValue
+import kotlinx.android.synthetic.main.include_transfer_summary.transfer_data_safe_balance_before_value as balanceBeforeValue
+import kotlinx.android.synthetic.main.screen_2fa_disable_start.disable_2fa_back_button as backArrow
+import kotlinx.android.synthetic.main.screen_2fa_disable_start.disable_2fa_coordinator as coordinator
+import kotlinx.android.synthetic.main.screen_2fa_disable_start.disable_2fa_bottom_panel as bottomPanel
+import kotlinx.android.synthetic.main.screen_2fa_disable_start.disable_2fa_progress_bar as progressBar
+
+class Remove2FaStartActivity : ViewModelActivity<PairingAuthenticatorContract>() {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt]: This is very much the same as `Connect2FaStartActivity` should we combine them?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/helpers/RecoverSafeOwnersHelper.kt [hunk 44]
```diff
@@ -114,8 +114,10 @@ class DefaultRecoverSafeOwnersHelper @Inject constructor(
                     .map { accounts ->
                         val account0 = accounts[0]
                         val account1 = accounts[1]
-                        val expectedOwnerCount = authenticatorAddress?.let { 4 } ?: 3
-                        check(safeInfo.owners.size == expectedOwnerCount)
+
+                        val expectedOwnerCount = 3//authenticatorAddress?.let { 4 } ?: 3
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/helpers/RecoverSafeOwnersHelper.kt]: Why this?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 45]
```diff
@@ -0,0 +1,193 @@
...
+
+    override fun estimate() {
+
+        viewModelScope.launch(appDispatcher.background + errorHandler) {
+
+            val paymentToken = tokenRepository.loadPaymentToken(safeAddress).await()
+
+            safeInfo = gnosisSafeRepository.loadInfo(safeAddress).awaitFirst()
+
+            val owner = accountsRepository.signingOwner(safeAddress).await()//safeInfo.owners[0]
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: What does this comment mean?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 46]
```diff
@@ -0,0 +1,193 @@
...
+            val extension = Solidity.Address(BigInteger.valueOf(Long.MAX_VALUE))
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Can we add a comment here

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 47]
```diff
@@ -0,0 +1,193 @@
...
+            val pairingTransaction = recoverSafeOwnersHelper.buildRecoverTransaction(
+                safeInfo,
+                safeInfo.owners.subList(2, safeInfo.owners.size).toSet(),
+                setOf(owner.address, extension)
+            )
+
+            val safeOwner = accountsRepository.signingOwner(safeAddress).await()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: We do we need to get the signing owner again here?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticatorActivity.kt [hunk 48]
```diff
@@ -0,0 +1,155 @@
...
+            when (it) {
+
+                is PairingAuthenticatorContract.ViewUpdate.Pairing -> {
+
+                    onPairingLoading(it.isLoading)
+
+                    it.pairingResult?.let {
+                        when(it) {
+                            is PairingAuthenticatorContract.PairingResult.PairingSuccess -> {
+                                //toast(R.string.devices_paired_successfuly)
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticatorActivity.kt]: Remove unused code

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt [hunk 49]
```diff
@@ -0,0 +1,193 @@
...
+
+                )
+            )
+        }
+    }
+
+
+    override fun loadAuthenticatorInfo() {
+
+        viewModelScope.launch(appDispatcher.background + errorHandler) {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: Should we have some kind of loading spinner?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt [hunk 50]
```diff
@@ -0,0 +1,135 @@
...
+
+
+                is PairingAuthenticatorContract.ViewUpdate.Authenticator -> {
+                    startActivity(RemoveAuthenticatorRecoveryPhraseActivity.createIntent(this, safe, it.info))
+                }
+
+            }
+        })
+
+        lifecycleScope.launchWhenStarted {
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt]: Do we need this scope here?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt [hunk 51]
```diff
@@ -0,0 +1,135 @@
...
+            viewModel.estimate()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt]: What happens if you change the payment token?

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt [hunk 52]
```diff
@@ -0,0 +1,129 @@
...
+                    progressBar.visibility = View.GONE
+                    balanceBeforeValue.text = it.balanceBefore
+                    feesValue.text = it.fee.underline()
+                    balanceAfterValue.text = it.balanceAfter
+                }
+            }
+        })
+
+        lifecycleScope.launchWhenStarted {
+            viewModel.estimate()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: Should this be called onStart so that it refreshes in case something changes (e.g. payment token)

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt [hunk 53]
```diff
@@ -0,0 +1,135 @@
...
+
+        backArrow.setOnClickListener {
+            finish()
+        }
+
+        feesValue.setOnClickListener {
+            startActivity(PaymentTokensActivity.createIntent(this, safe))
+        }
+
+        disposables += feesInfo.clicks()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Remove2FaStartActivity.kt]: Why do we use disposables here and click listeners for the rest?

File: app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt [hunk 54]
```diff
@@ -167,6 +168,22 @@ class ReviewTransactionActivity : ViewModelActivity<ReviewTransactionContract>()
         }
     }
 
+    override fun onConfirmationDialogDismiss() {
+        // If we have a reference id then we have been opened from a external request and should just close the screen without opening a new one
+
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/transactions/view/review/ReviewTransactionActivity.kt]: new line

File: app/src/test/java/pm/gnosis/heimdall/ui/safe/helpers/DefaultRecoverSafeOwnersHelperTest.kt [hunk 55]
```diff
@@ -175,15 +175,15 @@ class DefaultRecoverSafeOwnersHelperTest {
...
-    @Test
-    fun processInvalidOwnerCountWithExtension() {
-        testProcessInvalidOwnerCount(TEST_EXTENSION, listOf(TEST_OWNER, TEST_RECOVER_1, TEST_RECOVER_2))
-    }
-
-    @Test
-    fun processInvalidOwnerCountWithoutExtension() {
-        testProcessInvalidOwnerCount(null, listOf(TEST_OWNER, TEST_EXTENSION, TEST_RECOVER_1, TEST_RECOVER_2))
-    }
+//    @Test
```
Comment (rmeissner) [inline app/src/test/java/pm/gnosis/heimdall/ui/safe/helpers/DefaultRecoverSafeOwnersHelperTest.kt]: Why are these commented out?

File: app/src/main/AndroidManifest.xml (hunk 30 above)
Comment (elgatovital) [reply app/src/main/AndroidManifest.xml]: yes, makes sence

File: app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt (hunk 32 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/di/modules/ApplicationModule.kt]: I am for avoiding. This could be good candidate for a custom lint rule

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt (hunk 52 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: we should call it in on resume then

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt [hunk 56]
```diff
@@ -0,0 +1,156 @@
+package pm.gnosis.heimdall.ui.safe.connect
```
[the remark this answers is not in the document]
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: moved. Also currently authenticator and 2fa terms are mixed in a project. We have ui.authenticator package where authenticator stands for 2fa actually. I would use following:

[the remark this answers is not in the document]
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/connect/Connect2FaStartActivity.kt]: ui.authenticator -> ui.two_factor

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt [hunk 57]
```diff
@@ -0,0 +1,238 @@
...
+    @StringRes
+    fun titleRes(): Int = R.string.pair_2fa_device
+
+    fun onSuccess(signingOwner: AccountsRepository.SafeOwner, extension: Solidity.Address) {
+        val authenticatorInfo = AuthenticatorSetupInfo(signingOwner, AuthenticatorInfo(AuthenticatorInfo.Type.EXTENSION, extension))
+        setResult(Activity.RESULT_OK, authenticatorInfo.put(Intent()))
+        finish()
+    }
+
+    fun signingSafe(): Solidity.Address? = intent.getStringExtra(EXTRA_SAFE)?.asEthereumAddress()
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt]: Unused code

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt [hunk 58]
```diff
@@ -0,0 +1,238 @@
...
+
+    companion object {
+        private const val EXTRA_SAFE = "extra.string.safe"
+        private const val EXTRA_ONBOARDING = "extra.boolean.onboarding"
+        fun createIntent(context: Context, safe: Solidity.Address?, onboarding: Boolean = false) =
+            Intent(context, PairingAuthenticatorActivity::class.java).apply {
+                putExtra(EXTRA_SAFE, safe?.asEthereumAddressString())
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt]: Why is the `safe` optional here if we close the activity if not provided?

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt [hunk 59]
```diff
@@ -0,0 +1,238 @@
...
+    )
+}
+
+class PairingAuthenticatorViewModel @Inject constructor(
+    private val pushServiceRepository: PushServiceRepository,
+    private val moshi: Moshi,
+    private val appDispatcher: ApplicationModule.AppCoroutineDispatchers
+) : PairingAuthenticatorContract() {
+
+    private val errorHandler = CoroutineExceptionHandler { _, e ->
```
[the remark this answers is not in the document]
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt]: no, its useless here

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt [hunk 60]
```diff
@@ -0,0 +1,213 @@
...
+
+            it.pairingResult?.let {
+                when (it) {
+                    is PairingAuthenticatorContract.PairingResult.PairingSuccess -> {
+                        setResult(Activity.RESULT_OK, it.setpInfo.put(Intent()))
+                        finish()
+                    }
+
+                    is PairingAuthenticatorContract.PairingResult.PairingError -> {
+                        snackbar(pairing_coordinator, R.string.error_pairing_devices)
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/two_factor/authenticator/PairingAuthenticatorActivity.kt]: There is an `AppUtils.errorSnackbar` that should be used here

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt (hunk 49 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/safe/pairing/PairingAuthenticator.kt]: there shouldn't be any noticeable delay for the user

File: app/src/main/AndroidManifest.xml [hunk 61]
```diff
@@ -282,37 +306,37 @@
...
 
         <activity
-            android:name=".ui.authenticator.SelectAuthenticatorActivity"
+            android:name=".ui.two_factor.Select2FaActivity"
             android:screenOrientation="portrait"
             android:theme="@style/GreyBackgroundTheme" />
 
         <activity
-            android:name=".ui.keycard.KeycardIntroActivity"
+            android:name="pm.gnosis.heimdall.ui.two_factor.keycard.KeycardIntroActivity"
```
Comment (rmeissner) [inline app/src/main/AndroidManifest.xml]: this looks like a refactoring "bug" ... no need for full path here

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt [hunk 62]
```diff
@@ -51,6 +51,9 @@ class ConnectAuthenticatorViewModel @Inject constructor(
             updateState(true) {
                 apply {
                     viewAction = ViewAction.StartActivity(
+                        /*TODO: adjust layout of review transaction ativity
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt]: What exactly needs to be adjusted? Can we create a follow up ticket for that?

File: app/src/main/res/layout/layout_keycard_intro.xml [hunk 63]
```diff
@@ -4,7 +4,7 @@
     xmlns:tools="http://schemas.android.com/tools"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
-    tools:background="@color/pale_grey_two">
+    android:background="@color/pale_grey_two">
```
Comment (rmeissner) [inline app/src/main/res/layout/layout_keycard_intro.xml]: Isn't this already set in the AndroidManifest? Do avoid overdraw we should not set it here

File: app/src/main/res/layout/layout_pairing.xml [hunk 64]
```diff
@@ -3,143 +3,23 @@
     xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
     xmlns:tools="http://schemas.android.com/tools"
-    android:id="@+id/layout_pairing_coordinator"
+    android:id="@+id/pairing_coordinator"
+    android:background="@color/pale_grey_two"
```
Comment (rmeissner) [inline app/src/main/res/layout/layout_pairing.xml]: same here, we should set this via the AndroidManifest

File: app/src/main/res/layout/screen_2fa_pairing_start.xml [hunk 65]
```diff
@@ -0,0 +1,150 @@
+<?xml version="1.0" encoding="utf-8"?>
+<androidx.constraintlayout.widget.ConstraintLayout
+    xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto"
+    xmlns:tools="http://schemas.android.com/tools"
+    android:id="@+id/pairing_coordinator"
+    android:background="@color/pale_grey_two"
```
Comment (rmeissner) [inline app/src/main/res/layout/screen_2fa_pairing_start.xml]: same here

File: app/src/main/res/layout/screen_pairing_review.xml [hunk 66]
```diff
@@ -0,0 +1,235 @@
+<?xml version="1.0" encoding="utf-8"?>
+<androidx.constraintlayout.widget.ConstraintLayout
+    xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:app="http://schemas.android.com/apk/res-auto"
+    xmlns:tools="http://schemas.android.com/tools"
+    android:id="@+id/review_coordinator"
+    android:layout_width="match_parent"
+    android:background="@color/pale_grey_two"
```
Comment (rmeissner) [inline app/src/main/res/layout/screen_pairing_review.xml]: same here

File: app/src/test/java/pm/gnosis/heimdall/ui/safe/pairing/PairingStartViewModelTest.kt [hunk 67]
```diff
@@ -0,0 +1,170 @@
...
+            tokenRepository,
+            transactionExecutionRepository,
+            testAppDispatchers
+        )
+
+        viewModel.setup(SAFE_ADDRESS)
+    }
+
+    @Test
+    fun estimate() {
```
Comment (rmeissner) [inline app/src/test/java/pm/gnosis/heimdall/ui/safe/pairing/PairingStartViewModelTest.kt]: Would be nice to have tests for error cases too

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt (hunk 62 above)
Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt]: yes - mostly colors & background. And submit button hast to be part of info panel according to mockups. Follow up ticket follows

File: app/src/main/res/layout/layout_keycard_intro.xml (hunk 63 above)
Comment (elgatovital) [reply app/src/main/res/layout/layout_keycard_intro.xml]: ok, using @style/GreyBackgroundTheme then

File: app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt (hunk 62 above)
Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt]: Ok I just saw that now: the connect flow should not require to use the recovery phrase, so it makes no sense to use the `PairingSubmitActivity` for that. Therefore we should remove `PairingAction.CONNECT`

The design adjustment of `ReviewTransactionActivity` is not specific to KeyCard but a general design adjustment, right?

Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt]: yes, here is the issue: https://app.zenhub.com/workspaces/gnosis-safe-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/490

Comment (rmeissner) [reply app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt]: Why not remove the connect enum in this pr (since it is added in this pr). Also the connect flow already uses the review activity, so no need to have that in the issue. Only the part about adjusting the design is really required.

Comment (elgatovital) [reply app/src/main/java/pm/gnosis/heimdall/ui/two_factor/Connect2FaActivity.kt]: adjusted

File: app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/RecoverSafe2FAActivity.kt [hunk 68]
```diff
@@ -3,28 +3,28 @@ package pm.gnosis.heimdall.ui.safe.recover.safe
...
+class RecoverSafe2FAActivity : Select2FaActivity() {
 
     override fun onAuthenticatorSetupInfo(info: AuthenticatorSetupInfo) {
-        val safeAddress = intent.getStringExtra(EXTRA_RECOVERING_SAFE)!!.asEthereumAddress()!!
+        val safeAddress = intent.getStringExtra(EXTRA_SAFE)!!.asEthereumAddress()!!
         startActivity(RecoverSafeRecoveryPhraseActivity.createIntent(this, safeAddress, info))
     }
 
     companion object {
-        private const val EXTRA_RECOVERING_SAFE = "extra.string.recovering_safe"
```
Comment (rmeissner) [inline app/src/main/java/pm/gnosis/heimdall/ui/safe/recover/safe/RecoverSafe2FAActivity.kt]: This was on purpose a different key
