### PR TITLE
Prevent access to null binding after view is destroyed

### LINKED ISSUE #830: [Android]Crash when the tx details is opened ( searching for the steps)
**Describe the bug**
The app is crashed when transaction details page is opened ( I scrolled transactions list before tx details opening??)
Firebase error -https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/android:io.gnosis.safe/issues/a9b74ced91055fd3553839da3c744f10?time=last-seven-days&sessionId=

**To Reproduce**
1. Go txs list
2. Scroll it
3. Open transaction details ( wait for a sec)

**Expected behavior**
The app should not be crashed

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android Version: 10
 - App Version 1.12.1 - 94 . Release candidate 819
- Prod, mainnet
- Safe 0x8675B754342754A30A2AeF474D114d8460bca19b

**Additional context**

### PR DESCRIPTION
**Pull request by biafra23**
Closes #830  .

Changes proposed in this pull request:
- Page loading might return after switching to detail view and after `onDestroyView()` has been called and binding has been nulled Only access binding when this view is still at least STARTED
- Preventing submission in `loadTransactions()` unfortunately is not enough
- 

@gnosis/mobile-devs

### CODE REVIEW

File: app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt [hunk 1]
```diff
@@ -51,8 +52,10 @@ class TransactionListFragment : SafeOverviewBaseFragment<FragmentTransactionList
         super.onViewCreated(view, savedInstanceState)
 
         adapter.addLoadStateListener { loadState ->
-            binding.transactions.isVisible = loadState.refresh is LoadState.NotLoading
-            binding.progress.isVisible = loadState.refresh is LoadState.Loading
+            if (lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED)) {
```
Comment (elgatovital) [inline app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt:55]: this should be added also to adapter.addDataRefreshListener

Comment (biafra23) [reply app/src/main/java/io/gnosis/safe/ui/transactions/TransactionListFragment.kt:55]: Done in 326ae7b0ef245854436e0dba1d1331b46e414f57

**Review by elgatovital — APPROVED** [review]
